name: Run tests

on: [push]

jobs:
    run-tests:
        name: Run tests
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mariadb:10.4
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
                    MYSQL_DATABASE: rizkhal_testing
                    MYSQL_ROOT_PASSWORD: testing
                    MYSQL_PASSWORD: testing
                ports:
                - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10        

        steps:
            -   uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: '7.4'
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}

            -   name: Run composer install
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            -   name: Execute tests
                run: ./vendor/bin/phpunit
                env:
                  DB_PORT: ${{ job.services.mariadb.ports[3306] }}
                  DB_DATABASE: rizkhal_testing
                  DB_USERNAME: testing
                  DB_PASSWORD: testing
